// https://www.freepascal.org/docs-html/rtl/sysutils/ansilowercase.html
function AnsiLowerCase(const s: String): String;

// https://www.freepascal.org/docs-html/rtl/sysutils/ansiuppercase.html
function AnsiUpperCase(const s: String): String;

// https://www.freepascal.org/docs-html/rtl/system/compareword.html
function CompareWord(const buf1; const buf2; len: SizeInt): SizeInt;

// https://www.freepascal.org/docs-html/rtl/sysutils/gettickcount64.html
function GetTickCount64: QWord;


