
const

{ Foreground and background color constants }

  BLACK                 = $0;
  WHITE                 = $1;
  RED                   = $2;
  CYAN                  = $3;
  PURPLE                = $4;
  GREEN                 = $5;
  BLUE                  = $6;
  YELLOW                = $7;
  ORANGE                = $8;
  BROWN                 = $9;
  YELLOW_GREEN          = $A;
  PINK                  = $B;
  BLUE_GREEN            = $C;
  LIGHT_BLUE            = $D;
  DARK_BLUE             = $E;
  LIGHT_GREEN           = $F;
