const
    PLAYERS_NUM = 4;
    PLAYER_TYPES = 5;
    PLAYER_HUMAN = 0;
    PLAYER_CPU1 = 1;
    PLAYER_CPU2 = 2;
    PLAYER_CPU3 = 3;
    PLAYER_NONE = 4;
    
    P1COLOR = $26;
    P2COLOR = $16;
    P3COLOR = $e6;
    P4COLOR = $d6;
    BGCOLOR = $d0;
    ROLLMENUCOLOR = $c4;
    SCOREMENUCOLOR = $9c;
    BLINKCOLOR = $d6;
    
    MENU_SCORE1 = 1;
    MENU_SCORE2 = 2;
    // MENU_SCORE3 = 3;
    MENU_ROLL = $10;
    MENU_BANK = $20;
    MENU_QUIT = $40;
    MENU_NONE = 0;
  
var HELPFG: byte absolute $2DC;
