  {$i include/opt6502/opt_SHR_BYTE.inc}
  {$i include/opt6502/opt_SHR_WORD.inc}
  {$i include/opt6502/opt_SHR_CARD.inc}
  {$i include/opt6502/opt_SHL_BYTE.inc}
  {$i include/opt6502/opt_SHL_WORD.inc}
  {$i include/opt6502/opt_SHL_CARD.inc}
  {$i include/opt6502/opt_BYTE_DIV.inc}

  {$i include/opt6502/opt_STA_0.inc}
  {$i include/opt6502/opt_STACK.inc}
  {$i include/opt6502/opt_STACK_INX.inc}
  {$i include/opt6502/opt_STACK_ADD.inc}
  {$i include/opt6502/opt_STACK_CMP.inc}
  {$i include/opt6502/opt_STACK_ADR.inc}
  {$i include/opt6502/opt_STACK_AL_CL.inc}
  {$i include/opt6502/opt_STACK_AX_CX.inc}
  {$i include/opt6502/opt_STACK_EAX_ECX.inc}
  {$i include/opt6502/opt_STACK_PRINT.inc}
  {$i include/opt6502/opt_CMP_BRANCH.inc}
  {$i include/opt6502/opt_CMP_BP2.inc}
  {$i include/opt6502/opt_CMP_LOCAL.inc}
  {$i include/opt6502/opt_CMP_LT_GTEQ.inc}
  {$i include/opt6502/opt_CMP_LTEQ.inc}
  {$i include/opt6502/opt_CMP_GT.inc}
  {$i include/opt6502/opt_CMP_NE_EQ.inc}
  {$i include/opt6502/opt_CMP.inc}
  {$i include/opt6502/opt_CMP_0.inc}


